regions:
    login:
        url: /Account/api/form/FooAccount-Login
        partial: Account/forms/login.hbs
        type: Form
    create:
        url: /Account/api/form/FooAccount-Account
        partial: Account/forms/account.hbs
        type: Form
    forgot:
        url: /Account/api/form/FooAccount-Forgot
        partial: Account/forms/forgot.hbs
        type: Form