topics:
    'FORM:SAVE:FooAccount-Login':
        - accountModel@login
    'FORM:SAVE:FooAccount-Forgot':
        - accountModel@forgot
    'FORM:SAVE:FooAccount-Account':
        - accountModel@account