form:
    slug: FooAccount-Login
    fields:
        email:
            placeholder: Email
            display: fieldText@render
            required: true

        password:
            placeholder: Password
            display: fieldPassword@render
            required: true